[project]
name = "definitions"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "markdown==3.7",
    "pyrdfa3==3.5.3",
    "rdflib==6.1.1",
    "requests==2.32.3",
    "setuptools==70.0.0",
]
