prefix swe: <https://id.kb.se/term/swepub/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

insert {
    ?term skos:inScheme <https://id.kb.se/term/swepub>
} where {
    ?term ?p ?o
    filter ((?term != swe:) && strstarts(str(?term), str(swe:)))
};