prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix mads: <http://www.loc.gov/mads/rdf/v1#>

construct {
    ?s a ?type;
        skos:prefLabel ?label;
        skos:notation ?not;
        skos:exactMatch ?match .
} where {
    ?s a ?type;
        mads:code ?not;
        mads:authoritativeLabel ?label;
        mads:hasExactExternalAuthority ?match .
}
