prefix skos: <http://www.w3.org/2004/02/skos/core#>

construct {
    ?s ?p ?o ;
        skos:prefLabel ?prefLabel ;
        skos:definition ?definition .
} where {
    graph <https://id.kb.se/dataset/tacnotationterms> {
        ?s ?p ?o ; skos:exactMatch ?rda .
        optional {
            graph <http://rdaregistry.info/termList/TacNotation.nt> {
                ?rda skos:prefLabel ?prefLabel ;
                    skos:definition ?definition .
                filter(lang(?prefLabel) != 'sv')
            }
        }
    }
}