prefix : <http://schema.org/>
prefix madsrdf: <http://www.loc.gov/mads/rdf/v1#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix dc: <http://purl.org/dc/terms/>

construct {
    ?s ?p ?o ;
        skos:exactMatch ?loc ;
        skos:prefLabel ?prefLabel .

} where {
    graph <https://id.kb.se/dataset/countries> {
        {
            {
                ?s ?p ?o .
            } union {
                ?s skos:notation ?notation .
                graph <http://id.loc.gov/vocabulary/countries> {
                    ?loc madsrdf:authoritativeLabel|skos:prefLabel ?prefLabel .
                    filter strends(str(?loc), concat('/', ?notation))
                }
            }
        }
    }
}
