prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix : <https://id.kb.se/vocab/>
prefix marc: <https://id.kb.se/marc/>

construct {

    ?class rdfs:subClassOf ?restriction .

    ?restriction a owl:Restriction ;
        owl:onProperty ?property ;
        owl:someValuesFrom ?enumclass .

} where {

    values (?property ?class ?enumclass) {

(:additionalType	:Cartography	marc:MapsFormatType)
(:baseMaterial	:Globe	marc:GlobeMediumType)
(:baseMaterial	:Map	marc:MapMediumType)
(:baseMaterial	:Microform	marc:FilmBaseType)
(:baseMaterial	:MovingImage	marc:FilmBaseType)
(:baseMaterial	:ProjectedImage	marc:ProjGraphEmulsionType)
(:baseMaterial	:StillImage	marc:NonProjectedType)
(:carrierType	:Audio	marc:ItemType)
(:carrierType	:Cartography	marc:ItemType)
(:carrierType	:Digital	marc:ComputerItemType)
(:carrierType	:Electronic	marc:ComputerMaterialType)
(:carrierType	:Kit	marc:KitMaterialType)
(:carrierType	:Microform	marc:MicroformMaterialType)
(:carrierType	:Mixed	marc:ItemType)
(:carrierType	:MovingImage	marc:MotionPicMaterialType)
(:carrierType	:NotatedMusic	marc:KitMaterialType)
(:carrierType	:ProjectedImage	marc:ProjGraphMaterialType)
(:carrierType	:RemoteSensingImage	marc:KitMaterialType)
(:carrierType	:Serial	marc:ItemType)
(:carrierType	:SoundRecording	marc:SoundMaterialType)
(:carrierType	:Text	marc:BooksItemType)
(:carrierType	:Text	marc:TextMaterialType)
(:carrierType	:VideoRecording	marc:VideoMaterialType)
(:carrierType	:Visual	marc:ItemType)
(:cartographicAttributes	:Cartography	marc:MapsReliefType)
(:colorContent	:Electronic	marc:ComputerColorType)
(:colorContent	:Globe	marc:MapColorType)
(:colorContent	:Map	marc:MapColorType)
(:colorContent	:Microform	marc:MicroformColorType)
(:colorContent	:MovingImage	marc:MotionPicColorType)
(:colorContent	:ProjectedImage	marc:ColorType)
(:colorContent	:StillImage	marc:ColorType)
(:colorContent	:VideoRecording	marc:VideoColorType)
(:contentType	:Digital	marc:ComputerTypeOfFileType)
(:contentType	:Serial	marc:SerialsTypeOfSerialType)
(:contentType	:Text	marc:BooksContentsType)
(:contentType	:Visual	marc:VisualMaterialType)
(:descriptionConventions	:Record	marc:CatFormType)
(:descriptionConventions	:Record	marc:CatalogingRulesType)
(:dimensions	:Electronic	marc:ComputerDimensionsType)
(:dimensions	:Microform	marc:MicroformDimensionsType)
(:dimensions	:MovingImage	marc:MotionPicDimensionsType)
(:dimensions	:ProjectedImage	marc:ProjGraphDimensionsType)
(:dimensions	:SoundRecording	marc:SoundDimensionsType)
(:dimensions	:SoundRecording	marc:SoundTapeWidthType)
(:dimensions	:VideoRecording	marc:VideoDimensionsType)
(:emulsion	:Microform	marc:MicroformEmulsionType)
(:frequency	:Serial	marc:SerialsFrequencyType)
(:frequency	:Serial	marc:SerialsRegularityType)
(:generation	:Microform	marc:MicroformGenerationType)
(:generation	:MovingImage	marc:MotionPicGenerationType)
(:generation	:SoundRecording	marc:SoundKindOfDiscType)
(:genreForm	:Audio	marc:MusicCompositionType)
(:genreForm	:Audio	marc:MusicTextType)
(:genreForm	:Cartography	marc:GovernmentPublicationType)
(:genreForm	:Digital	marc:ComputerTypeOfFileType)
(:genreForm	:Digital	marc:GovernmentPublicationType)
(:genreForm	:Globe	marc:GlobeMaterialType)
(:genreForm	:Map	marc:MapMaterialType)
(:genreForm	:MovingImage	marc:MotionPicElementsType)
(:genreForm	:Serial	marc:GovernmentPublicationType)
(:genreForm	:Serial	marc:SerialsContentsType)
(:genreForm	:Serial	marc:SerialsNatureType)
(:genreForm	:Serial	marc:SerialsTypeOfSerialType)
(:genreForm	:StillImage	marc:NonProjMaterialType)
(:genreForm	:Text	marc:BooksBiographyType)
(:genreForm	:Text	marc:BooksFestschriftType)
(:genreForm	:Text	marc:BooksLiteraryFormType)
(:genreForm	:Text	marc:ConferencePublicationType)
(:genreForm	:Text	marc:GovernmentPublicationType)
(:genreForm	:Visual	marc:GovernmentPublicationType)
(:genreForm	:Visual	marc:VisualMaterialType)
(:illustrativeContent	:Text	marc:BooksIllustrationsType)
(:intendedAudience	:Audio	marc:AudienceType)
(:intendedAudience	:Digital	marc:AudienceType)
(:intendedAudience	:Text	marc:AudienceType)
(:intendedAudience	:Visual	marc:AudienceType)
(:mount	:ProjectedImage	marc:ProjGraphSupportType)
(:mount	:StillImage	marc:NonProjectedType)
(:musicFormat	:Audio	marc:MusicFormatType)
(:polarity	:Microform	marc:PolarityType)
(:polarity	:MovingImage	marc:MotionPicPosNegType)
(:projection	:Cartography	marc:MapsProjectionType)
(:projectionCharacteristic	:Cartography	marc:MapsProjectionType)
(:projectionCharacteristic	:MovingImage	marc:MotionPicFormatType)
(:reductionRatio	:Microform	marc:MicroformRangeType)
(:soundCharacteristic	:MovingImage	marc:MediumType)
(:soundCharacteristic	:MovingImage	marc:MotionPicConfigurationOrVideoPlaybackType)
(:soundCharacteristic	:ProjectedImage	marc:MediumType)
(:soundCharacteristic	:SoundRecording	marc:SoundGrooveType)
(:soundCharacteristic	:SoundRecording	marc:SoundKindOfCuttingType)
(:soundCharacteristic	:SoundRecording	marc:SoundPlaybackChannelType)
(:soundCharacteristic	:SoundRecording	marc:SoundPlaybackCharacterType)
(:soundCharacteristic	:SoundRecording	marc:SoundSpeedType)
(:soundCharacteristic	:SoundRecording	marc:SoundTapeConfigurationType)
(:soundCharacteristic	:VideoRecording	marc:MediumType)
(:soundCharacteristic	:VideoRecording	marc:MotionPicConfigurationOrVideoPlaybackType)
(:soundContent	:Electronic	marc:ComputerSoundType)
(:soundContent	:MovingImage	marc:SoundType)
(:soundContent	:ProjectedImage	marc:SoundType)
(:soundContent	:VideoRecording	marc:SoundType)
(:supplementaryContent	:Audio	marc:MusicMatterType)
(:supplementaryContent	:Cartography	marc:IndexType)
(:supplementaryContent	:Text	marc:IndexType)
(:videoCharacteristic	:VideoRecording	marc:VideoFormatType)

    }

    bind(bnode(concat(str(?class), str(?property))) as ?restriction)

}
