prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix : <https://id.kb.se/vocab/>

insert { #:
    # :Resource as baseclass of a term
    ?term rdfs:subClassOf :Resource

} where { #:
    # term is a class...
    ?term a owl:Class .

    # defined in : (kbv)...
    filter strstarts(str(?term), str(:))

    # unless it *is* that class...
    filter(?term != :Resource)

    # and as long as it is *not* the case that:
    filter not exists {
      # another baseclass is defined...
      ?term rdfs:subClassOf ?baseclass .
      # which is identified by an IRI...
      filter isURI(?baseclass)
      # and is defined by : (kbv).
      filter strstarts(str(?baseclass), str(:))
    }
}
