prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix : <https://id.kb.se/vocab/>

insert {
    ?term rdfs:isDefinedBy :
} where {
    ?term ?p ?o
    filter ((?term != :) && strstarts(str(?term), str(:)))
};

delete {
    ?s ?p rdfs:Resource
} where {
    ?s ?p ?o
    filter(?o != rdfs:Resource && strstarts(str(?o), str(:)))
    filter(?p in (rdfs:subClassOf, rdfs:domain, rdfs:range))
};

# remove redundant base classes
delete {
    ?c rdfs:subClassOf ?a .
} where {
    ?c rdfs:subClassOf / rdfs:subClassOf+ ?a .
}
